### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by darkimage404** [jonyrh/OXR_Switcher#1]
Great work, my absolute favorite!
can we have a command line argument to change directly?

OXR_Switcher.exe /oculus

OXR_Switcher.exe /virtualdesktop

OXR_Switcher.exe /steamvr

UAC access is not avoidable right?
regkey is inside HKLM so admin permissions are needed

**Comment by djsolidsnake86** [comment]
i second this request!

**Comment by jonyrh** [comment]
Hi, ok, i adding command line! Yes UAC warning message not disable, but if you're user in local Administrator then warning message missing. 
Or this:
![image](https://github.com/jonyrh/OXR_Switcher/assets/28771126/22ff9bdb-516e-4858-aff8-0ea062b4145a)

**Comment by jonyrh** [comment]
Done, injoy [Release 2024.06.22.19](https://github.com/jonyrh/OXR_Switcher/releases/tag/2024.06.22.19)
PS: see new description

**Comment by djsolidsnake86** [comment]
> Done, injoy [Release 2024.06.22.19](https://github.com/jonyrh/OXR_Switcher/releases/tag/2024.06.22.19) PS: see new description

hello i can't understand how use correctly the command prompt line

**Comment by jonyrh** [comment]
@djsolidsnake86 

![image](https://github.com/jonyrh/OXR_Switcher/assets/28771126/ca551994-ea39-4357-9697-a32a31faeb35)
